### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by CeleritasCelery** [tromey/emacs-ffi#23]
Currently this project has no license, which means [no one is able to use it or work on it](https://opensource.stackexchange.com/a/1721). Please consider adding an Open Source license to the repo.

**Comment by vonHabsi** [comment]
Is this statute law, or is that Github's own take on the law?

Would that be the case if the code was hosted somewhere else besides Github?

**Comment by CeleritasCelery** [comment]
Everything in the law is an interpretation so, IANAL,TINLA. 

When you create something (include code) you own the rights to it. No one else can use that thing without express permission. If I tried to edit or even run this code @tromey could sue me for infringement. 

To prevent this people can give explicit permission to others to use their stuff (usually in the form of a license). Without permission it would be illegal. This has nothing to do with GitHub, and [would apply no matter where the code was hosted](https://choosealicense.com/no-permission/). This is why [license hygiene](https://choosealicense.com/) is so important.

**Comment by suhail-singh** [comment]
@tromey I am considering packaging this project within Guix.  However, at
present the license for it hasn't been made explicit.  Would you be able to
please confirm whether you are open to releasing it under some permissive
license?

On a related note, in case you're not aware, recent discussions in emacs-devel
suggest that the Emacs project would be unwilling to merge this project
upstream.  The reasons for this have to do with the project's ethical stance.

Specifically, for the Emacs project, a user's verification of the GPL compliance
for a used library is not sufficient. Given the lack of a standardized method
for shared libraries to declare their licenses, projects like `emacs-ffi` can,
at most, only request confirmation from users. This approach, however, falls
short of the standards expected by the Emacs project.

However, `emacs-ffi` _does_ provide value - it enables a way for users to do
iterative development.  However, its full potential remains unrealized due to
the absence of a clear and explicit software license.  I am hopeful that we can
rectify this in short order.

Cheers
